- name: Add hosts to known_hosts file
  hosts: all
  # gather_facts: yes

  tasks:
    - name: Add hosts to known_hosts
      known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ item }}"  # Use the hostname from the inventory
        key: "{{ hostvars[item].ansible_host }}"  # Use the SSH key of the host
        key_options: "port=22"  # Specify the SSH port (default is 22)
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups['nomad_servers'] + groups['nomad_clients'] }}"

- name: Ubuntu Server Setup
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist