---
- name: Prepare Servers
  hosts: all
  remote_user: root
  roles:
    - role: common

- name: Install nomad and consul
  hosts: all
  remote_user: root
  roles:
    - role: hashicorp

- name: Configure Nomad clients
  hosts: nomad_clients
  remote_user: root
  tasks:
    - name: Log server IPs
      ansible.builtin.debug:
        msg: "Server IPs are: {{ server_ips }}"
  #   - name: Configure client nomad.hcl
  #     ansible.builtin.import_tasks: roles/hashicorp/tasks/nomad-server.yml

- name: Install podman
  hosts: nomad_clients
  remote_user: root
  roles:
    - role: podman
