- name: Add hosts to known_hosts file
  hosts: all
  tasks:
    - name: Add hosts to known_hosts
      known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ item }}"
        key: "{{ hostvars[item].ansible_host }}"
        key_options: "port=22"
      when: hostvars[item].ansible_host is defined
      loop: "{{ groups['nomad_servers'] + groups['nomad_clients'] }}"

- name: Ubuntu Server Setup
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

- name: Install necessary packages
  hosts: all
  tasks:
    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - wget
          - gpg
          - curl
          - coreutils
          - jq
        state: present
# - name: Set up UFW Firewall
#   hosts: all
#   tasks:
#     - name: Set up UFW Firewall
#       ansible.builtin.ufw:
#         state: enabled
#         default: deny
#         direction: in
#         rule: allow
#         port: 22
#       notify: restart sshd

#   handlers:
#     - name: restart sshd
#       ansible.builtin.service:
#         name: sshd
#         state: restarted
# - name: Setup Specific for Nomad Servers
#   hosts: nomad_servers
#   become: yes
#   tasks:
#     # Add tasks specific to Nomad servers here

# - name: Setup Specific for Nomad Clients
#   hosts: nomad_clients
#   become: yes
#   tasks:
#     # Add tasks specific to Nomad clients here

# - name: Setup for Nomad Load Balancers
#   hosts: nomad_load_balancers
#   become: yes
#   tasks:
# Add tasks specific to Nomad load balancers here
