---
- name: Prepare Servers
  hosts: all
  remote_user: root
  roles:
    - role: common

- name: Install nomad and consul
  hosts: all
  become: true
  roles:
    - role: hashicorp

- name: install podman
  hosts: nomad_clients
  become: true
  roles:
    - role: podman
