---
- name: Prepare Servers
  hosts: all
  remote_user: root
  roles:
    - role: common

- name: Install nomad and consul
  hosts: all
  become: true
  roles:
    - role: hashicorp

- name: install podman
  hosts: nomad_clients
  become: true
  roles:
    - role: podman
# - name: Setup Specific for Nomad Servers
#   hosts: nomad_servers
#   become: yes
#   tasks:
#     # Add tasks specific to Nomad servers here

# - name: Setup Specific for Nomad Clients
#   hosts: nomad_clients
#   become: yes
#   tasks:
#     # Add tasks specific to Nomad clients here

# - name: Setup for Nomad Load Balancers
#   hosts: nomad_load_balancers
#   become: yes
#   tasks:
# Add tasks specific to Nomad load balancers here
