---
- name: Update the package index
  ansible.builtin.apt:
    update_cache: true

- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Install or update Consul
  ansible.builtin.apt:
    name:
      - nomad
      - consul
    update_cache: yes
