---
- name: Get Internal IP Addresses
  hosts: nomad_servers
  remote_user: root
  gather_facts: true

  tasks:
    - name: Filter Internal IP Addresses
      ansible.builtin.debug:
        var: ansible_facts['ansible_all_ipv4_addresses']

- name: Prepare Servers
  hosts: all
  remote_user: root
  roles:
    - role: common

- name: Install and Configure Nomad
  hosts:
    - nomad_servers
    - nomad_clients
  remote_user: root
  roles:
    - nomad

- name: Install podman
  hosts: nomad_clients
  remote_user: root
  roles:
    - role: podman
