---
- name: Display all server IPs
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display all server IPs
      ansible.builtin.debug:
        msg: "Server IPs: {{ server_ips }}"

- name: Prepare Servers
  hosts: all
  remote_user: root
  roles:
    - role: common

- name: Install and Configure Nomad
  hosts:
    - nomad_servers
    - nomad_clients
  remote_user: root
  roles:
    - nomad

- name: Install podman
  hosts: nomad_clients
  remote_user: root
  roles:
    - role: podman
