name: Deploy to cloud.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.HCLOUD_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.HETZNER_BOX_KEY }}" > hetzner_box_key
          chmod 600 hetzner_box_key

      - name: Setup SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 23 -H ${{ secrets.HETZNER_BOX_HOST }} >> ~/.ssh/known_hosts

      - name: Download Terraform State with rsync
        run: |
          rsync -avz -e "ssh -i hetzner_box_key -p23" ${USER}@${HOST}:./terraform.tfstate .
        env:
          USER: ${{ secrets.HETZNER_BOX_USER }}
          HOST: ${{ secrets.HETZNER_BOX_HOST }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Upload Terraform State with rsync
        run: |
          rsync -avz -e "ssh -i hetzner_box_key -p23" ./terraform.tfstate ${USER}@${HOST}:./
        env:
          USER: ${{ secrets.HETZNER_BOX_USER }}
          HOST: ${{ secrets.HETZNER_BOX_HOST }}

      # Output IP addresses for clients and servers
      # - name: Output Client IPs
      #   id: client_ips
      #   run: echo "::set-output name=client_ips::$(terraform output -raw client_ips)"

      # - name: Output Server IPs
      #   id: server_ips
      #   run: echo "::set-output name=server_ips::$(terraform output -raw server_ips)"

      # - name: Run Ansible Playbook
      #   env:
      #     ANSIBLE_HOST_KEY_CHECKING: False
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   run: |
      #     echo "${SSH_PRIVATE_KEY}" > ansible_ssh_key
      #     chmod 600 ansible_ssh_key
      #     echo '[clients]' > dynamic_inventory
      #     echo ${{ steps.client_ips.outputs.client_ips }} >> dynamic_inventory
      #     echo '[servers]' >> dynamic_inventory
      #     echo ${{ steps.server_ips.outputs.server_ips }} >> dynamic_inventory
      #     ansible-playbook -i dynamic_inventory playbook.yml --private-key ansible_ssh_key
