name: Deploy to cloud.

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  terraform:
    name: Deploy stack.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.1
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}

      - name: install ansible dependencies
        run: ansible-galaxy install -r ansible-playbook/requirements.yml

      - name: Install Python dependencies
        run: |
          cd ansible-playbook 
          python -m venv playbook-venv
          source playbook-venv/bin/activate
          pip install -r requirements.txt

      - name: install ansible dependencies
        run: |
          cd ansible-playbook 
          source playbook-venv/bin/activate
          ansible-galaxy install -r requirements.yml

      - name: Run Ansible Playbook
        run: |
          cd ansible-playbook
          source playbook-venv/bin/activate
          ansible-playbook playbook.yml --private-key ../machines.pem
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
